### ISSUE TITLE
Pipeline created by Elyra fails with "ValueError: No template sub-directory with name 'lab' found in the following paths"

### ISSUE THREAD

**Issue by rimolive** [opendatahub-io/s2i-lab-elyra#49]
**Describe the bug**
When submitting a pipeline made from jupyter notebooks to an ML Pipelines runtime, the pipeline step fails with an unexpected error about templates. When the pipeline step finishes, an HTML output of the notebook using the `nbconvert` Python package is generated. However, this step fails because Elyra container image installs the package in the wrong path.

**To Reproduce**
1. Create a simple Jupyter notebook
2. Create a kubeflow pipeline editor
3. Drag and drop the notebook created in step 1. to the visual editor.
4. Create a runtime configuration pointint to an existing ML Pipelines environment
5. Click on Run pipelines, then OK.

**Expected behavior**
The pipeline should run with no errors in the ML Pipelines runtime side.

**Screenshots**
This [gist link](https://gist.github.com/rimolive/88a2d464c2308d954ea795d307b74280) shows the current error

**Additional context**
N/A

**Comment by ptitzler** [comment]
Can you please provide the following information:
 - the entire log file
 - which version of Elyra are you using? 
 - which container image have you configured as the "runtime image" in the notebook node? how did you create it? what packages are installed?
 - can you elaborate on what you mean by "[...] step fails because Elyra container image installs the package in the wrong path"

**Comment by harshad16** [comment]
With Elyra installed on the ODH workbench images directly.
Please refer ODH base notebook images, to utilize elyra.

Closing this issue. Feel free to open the issue on 
Reference: https://github.com/opendatahub-io/notebooks
